var annotated_dup =
[
    [ "qlibs", null, [
      [ "bitfield", "classqlibs_1_1bitfield.html", "classqlibs_1_1bitfield" ],
      [ "continuousSystem", "classqlibs_1_1continuous_system.html", "classqlibs_1_1continuous_system" ],
      [ "crc", "classqlibs_1_1crc.html", "classqlibs_1_1crc" ],
      [ "discreteSystem", "classqlibs_1_1discrete_system.html", "classqlibs_1_1discrete_system" ],
      [ "fp16", "classqlibs_1_1fp16.html", "classqlibs_1_1fp16" ],
      [ "ltisys", "classqlibs_1_1ltisys.html", "classqlibs_1_1ltisys" ],
      [ "pidAutoTuning", "classqlibs_1_1pid_auto_tuning.html", null ],
      [ "pidController", "classqlibs_1_1pid_controller.html", "classqlibs_1_1pid_controller" ],
      [ "pidGains", "structqlibs_1_1pid_gains.html", "structqlibs_1_1pid_gains" ],
      [ "rms", "classqlibs_1_1rms.html", "classqlibs_1_1rms" ],
      [ "smoother", "classqlibs_1_1smoother.html", "classqlibs_1_1smoother" ],
      [ "smootherALNF", "classqlibs_1_1smoother_a_l_n_f.html", "classqlibs_1_1smoother_a_l_n_f" ],
      [ "smootherDESF", "classqlibs_1_1smoother_d_e_s_f.html", "classqlibs_1_1smoother_d_e_s_f" ],
      [ "smootherEXPW", "classqlibs_1_1smoother_e_x_p_w.html", "classqlibs_1_1smoother_e_x_p_w" ],
      [ "smootherGMWF", "classqlibs_1_1smoother_g_m_w_f.html", "classqlibs_1_1smoother_g_m_w_f" ],
      [ "smootherKLMN", "classqlibs_1_1smoother_k_l_m_n.html", "classqlibs_1_1smoother_k_l_m_n" ],
      [ "smootherLPF1", "classqlibs_1_1smoother_l_p_f1.html", "classqlibs_1_1smoother_l_p_f1" ],
      [ "smootherLPF2", "classqlibs_1_1smoother_l_p_f2.html", "classqlibs_1_1smoother_l_p_f2" ],
      [ "smootherMOR1", "classqlibs_1_1smoother_m_o_r1.html", "classqlibs_1_1smoother_m_o_r1" ],
      [ "smootherMOR2", "classqlibs_1_1smoother_m_o_r2.html", "classqlibs_1_1smoother_m_o_r2" ],
      [ "smootherMWM1", "classqlibs_1_1smoother_m_w_m1.html", "classqlibs_1_1smoother_m_w_m1" ],
      [ "smootherMWM2", "classqlibs_1_1smoother_m_w_m2.html", "classqlibs_1_1smoother_m_w_m2" ],
      [ "state", "classqlibs_1_1state.html", "classqlibs_1_1state" ],
      [ "tdl", "classqlibs_1_1tdl.html", "classqlibs_1_1tdl" ]
    ] ],
    [ "fis", "classfis.html", "classfis" ],
    [ "fisInput", "classfis_input.html", null ],
    [ "fisMF", "classfis_m_f.html", null ],
    [ "fisOutput", "classfis_output.html", null ],
    [ "fisSystem", "classfis_system.html", "classfis_system" ],
    [ "sortStackNode", "structsort_stack_node.html", null ]
];