var searchData=
[
  ['scalar_20kalman_20filter_0',['Scalar Kalman filter',['../qssmoother_desc.html#qssmoother_klmn',1,'']]],
  ['scalar_20kalman_20filter_3a_1',['Example: setting up a scalar Kalman filter:',['../qssmoother_desc.html#qssmoother_ex9',1,'']]],
  ['second_20order_20low_20pass_20filter_2',['Second Order Low Pass Filter',['../qssmoother_desc.html#qssmoother_lpf2',1,'']]],
  ['setting_20up_20a_201st_20order_20low_20pass_20filter_3a_3',['Example: setting up a 1st order low-pass filter:',['../qssmoother_desc.html#qssmoother_ex1',1,'']]],
  ['setting_20up_20a_202nd_20order_20low_20pass_20filter_3a_4',['Example: setting up a 2nd order low-pass filter:',['../qssmoother_desc.html#qssmoother_ex2',1,'']]],
  ['setting_20up_20a_20gaussian_20filter_3a_5',['Example: setting up a gaussian filter:',['../qssmoother_desc.html#qssmoother_ex7',1,'']]],
  ['setting_20up_20a_20moving_20window_20median_20filter_3a_6',['Example: Setting up a moving window median filter:',['../qssmoother_desc.html#qssmoother_ex4',1,'']]],
  ['setting_20up_20a_20moving_20window_20median_20filter_3a_7',['Example: setting up a moving window median filter:',['../qssmoother_desc.html#qssmoother_ex3',1,'']]],
  ['setting_20up_20a_20scalar_20kalman_20filter_3a_8',['Example: setting up a scalar Kalman filter:',['../qssmoother_desc.html#qssmoother_ex9',1,'']]],
  ['setting_20up_20an_20exponential_20weighting_20filter_3a_9',['Example: setting up an exponential weighting filter:',['../qssmoother_desc.html#qssmoother_ex8',1,'']]],
  ['setting_20up_20an_20outlier_20removal_20filter_3a_10',['setting up an outlier removal filter:',['../qssmoother_desc.html#qssmoother_ex5',1,'Example: setting up an outlier removal filter:'],['../qssmoother_desc.html#qssmoother_ex6',1,'Example: setting up an outlier removal filter:']]],
  ['setting_20up_20the_20double_20exponential_20smoothing_3a_11',['Example: setting up the Double Exponential Smoothing:',['../qssmoother_desc.html#qssmoother_ex10',1,'']]],
  ['setup_12',['Instance setup',['../qbitfield_desc.html#qbitfield_setup',1,'']]],
  ['signal_20smoothing_13',['signal smoothing',['../qssmoother_desc.html#qssmoother_ex11',1,'Example of signal smoothing'],['../qssmoother_desc.html',1,'Filters for signal smoothing']]],
  ['single_20bit_14',['Single-bit',['../qbitfield_desc.html#qbitfield_sbit',1,'']]],
  ['smoothing_15',['Double Exponential Smoothing',['../qssmoother_desc.html#qssmoother_desf',1,'']]],
  ['smoothing_16',['smoothing',['../qssmoother_desc.html#qssmoother_ex11',1,'Example of signal smoothing'],['../qssmoother_desc.html',1,'Filters for signal smoothing']]],
  ['smoothing_3a_17',['Example: setting up the Double Exponential Smoothing:',['../qssmoother_desc.html#qssmoother_ex10',1,'']]],
  ['snippet_20that_20demonstrates_20the_20spline_20interpolation_18',['Example : Code snippet that demonstrates the spline interpolation .',['../qinterp1_desc.html#qinterp1_ex1',1,'']]],
  ['snippet_20to_20instantiate_20a_20tdl_20to_20hold_20up_20to_20256_20delays_19',['Example : Code snippet to instantiate a TDL to hold up to 256 delays.',['../qtdl_desc.html#qtdl_ex1',1,'']]],
  ['solution_20of_20the_20quadratic_20equation_20',['Example: Solution of the quadratic equation',['../qfp16_desc.html#qfp16_example',1,'']]],
  ['special_20functions_21',['Special functions',['../qffmath_desc.html#qffmath_special',1,'']]],
  ['speed_20control_20using_20a_20pid_20controller_3a_22',['Example: Speed control using a PID controller:',['../qpid_desc.html#qpid_ex1',1,'']]],
  ['speed_20control_20with_20pid_20controller_20and_20autotuning_3a_23',['Example: Speed control with PID controller and autotuning:',['../qpid_desc.html#qpid_ex3',1,'']]],
  ['speed_20control_20with_20pid_20controller_20with_20an_20additive_20mrac_3a_24',['Example: Speed control with PID controller with an additive MRAC:',['../qpid_desc.html#qpid_ex2',1,'']]],
  ['spline_20interpolation_25',['Example : Code snippet that demonstrates the spline interpolation .',['../qinterp1_desc.html#qinterp1_ex1',1,'']]],
  ['square_20estimator_26',['Recursive Root Mean Square estimator',['../qrms_desc.html',1,'index']]],
  ['structure_27',['Structure',['../qbitfield_desc.html#qbitfield_structure',1,'']]],
  ['sugeno_28',['Sugeno',['../qfis_desc.html#qfis_sugeno',1,'']]],
  ['support_29',['Arduino support',['../_arduino_01support.html',1,'']]],
  ['system_30',['Evaluating a Fuzzy Inference System',['../qfis_desc.html#qfis_eval',1,'']]],
  ['system_20engine_31',['Fuzzy Inference System Engine',['../qfis_desc.html',1,'index']]],
  ['system_20with_20delay_32',['Example: Continuous System with Delay',['../qltisys_desc.html#td_continuous',1,'']]],
  ['systems_20evaluation_20by_20transfer_20functions_33',['Recursive LTI Systems Evaluation by transfer functions.',['../qltisys_desc.html',1,'index']]]
];
