var searchData=
[
  ['calculator_20class_0',['Generic Cyclic Redundancy Check (CRC) calculator class',['../qcrc_desc.html',1,'index']]],
  ['check_20crc_20calculator_20class_1',['Generic Cyclic Redundancy Check (CRC) calculator class',['../qcrc_desc.html',1,'index']]],
  ['class_2',['class',['../qinterp1_desc.html',1,'1D Interpolation class'],['../qcrc_desc.html',1,'Generic Cyclic Redundancy Check (CRC) calculator class']]],
  ['classification_3',['Classification',['../qffmath_desc.html#qffmath_classify',1,'']]],
  ['code_20generation_4',['Code generation',['../qfis_desc.html#qfis_codegen',1,'']]],
  ['code_20snippet_20that_20demonstrates_20the_20spline_20interpolation_5',['Example : Code snippet that demonstrates the spline interpolation .',['../qinterp1_desc.html#qinterp1_ex1',1,'']]],
  ['code_20snippet_20to_20instantiate_20a_20tdl_20to_20hold_20up_20to_20256_20delays_6',['Example : Code snippet to instantiate a TDL to hold up to 256 delays.',['../qtdl_desc.html#qtdl_ex1',1,'']]],
  ['constants_7',['Constants',['../qffmath_desc.html#qffmath_const',1,'']]],
  ['continous_20time_20transfer_20functions_8',['Continous-time transfer functions',['../qltisys_desc.html#qltisys_cont',1,'']]],
  ['continuous_20system_20with_20delay_9',['Example: Continuous System with Delay',['../qltisys_desc.html#td_continuous',1,'']]],
  ['continuous_20transfer_20function_10',['Example: Evaluate the given continuous transfer function',['../qltisys_desc.html#qltisys_ex1',1,'']]],
  ['control_11',['Additive MRAC (Model Reference Adaptive Control)',['../qpid_desc.html#qpid_mrac',1,'']]],
  ['control_20using_20a_20pid_20controller_3a_12',['Example: Speed control using a PID controller:',['../qpid_desc.html#qpid_ex1',1,'']]],
  ['control_20with_20pid_20controller_20and_20autotuning_3a_13',['Example: Speed control with PID controller and autotuning:',['../qpid_desc.html#qpid_ex3',1,'']]],
  ['control_20with_20pid_20controller_20with_20an_20additive_20mrac_3a_14',['Example: Speed control with PID controller with an additive MRAC:',['../qpid_desc.html#qpid_ex2',1,'']]],
  ['controller_15',['Controller',['../qpid_desc.html#qpid_create',1,'Creating a PID Controller'],['../qpid_desc.html',1,'PID Controller']]],
  ['controller_16',['Using the controller',['../qpid_desc.html#qfpid_usage',1,'']]],
  ['controller_20and_20autotuning_3a_17',['Example: Speed control with PID controller and autotuning:',['../qpid_desc.html#qpid_ex3',1,'']]],
  ['controller_20approach_18',['PID Controller approach',['../qpid_desc.html#qpid_approach',1,'']]],
  ['controller_20with_20an_20additive_20mrac_3a_19',['Example: Speed control with PID controller with an additive MRAC:',['../qpid_desc.html#qpid_ex2',1,'']]],
  ['controller_3a_20',['Example: Speed control using a PID controller:',['../qpid_desc.html#qpid_ex1',1,'']]],
  ['conversion_21',['Using Time Conversion',['../qltisys_desc.html#td_timeconv',1,'']]],
  ['conversion_20functions_22',['Conversion functions',['../qfp16_desc.html#qfp16_conv_functions',1,'']]],
  ['crc_20calculator_20class_23',['Generic Cyclic Redundancy Check (CRC) calculator class',['../qcrc_desc.html',1,'index']]],
  ['creating_20a_20pid_20controller_24',['Creating a PID Controller',['../qpid_desc.html#qpid_create',1,'']]],
  ['cyclic_20redundancy_20check_20crc_20calculator_20class_25',['Generic Cyclic Redundancy Check (CRC) calculator class',['../qcrc_desc.html',1,'index']]]
];
