var searchData=
[
  ['tapped_20delay_20line_20in_20o_201_0',['Tapped Delay Line in O(1)',['../qtdl_desc.html',1,'index']]],
  ['tdl_20to_20hold_20up_20to_20256_20delays_1',['Example : Code snippet to instantiate a TDL to hold up to 256 delays.',['../qtdl_desc.html#qtdl_ex1',1,'']]],
  ['that_20demonstrates_20the_20spline_20interpolation_2',['Example : Code snippet that demonstrates the spline interpolation .',['../qinterp1_desc.html#qinterp1_ex1',1,'']]],
  ['the_20controller_3',['Using the controller',['../qpid_desc.html#qfpid_usage',1,'']]],
  ['the_20double_20exponential_20smoothing_3a_4',['Example: setting up the Double Exponential Smoothing:',['../qssmoother_desc.html#qssmoother_ex10',1,'']]],
  ['the_20given_20continuous_20transfer_20function_5',['Example: Evaluate the given continuous transfer function',['../qltisys_desc.html#qltisys_ex1',1,'']]],
  ['the_20given_20discrete_20transfer_20function_6',['Example: Evaluate the given discrete transfer function',['../qltisys_desc.html#qltisys_ex2',1,'']]],
  ['the_20quadratic_20equation_7',['Example: Solution of the quadratic equation',['../qfp16_desc.html#qfp16_example',1,'']]],
  ['the_20spline_20interpolation_8',['Example : Code snippet that demonstrates the spline interpolation .',['../qinterp1_desc.html#qinterp1_ex1',1,'']]],
  ['time_20conversion_9',['Using Time Conversion',['../qltisys_desc.html#td_timeconv',1,'']]],
  ['time_20transfer_20functions_10',['time transfer functions',['../qltisys_desc.html#qltisys_cont',1,'Continous-time transfer functions'],['../qltisys_desc.html#qltisys_disc',1,'Discrete-time transfer functions']]],
  ['timer_20interrupt_11',['Example : By using a timer interrupt',['../qrms_desc.html#qrms_ex1',1,'']]],
  ['to_20256_20delays_12',['Example : Code snippet to instantiate a TDL to hold up to 256 delays.',['../qtdl_desc.html#qtdl_ex1',1,'']]],
  ['to_20hold_20up_20to_20256_20delays_13',['Example : Code snippet to instantiate a TDL to hold up to 256 delays.',['../qtdl_desc.html#qtdl_ex1',1,'']]],
  ['to_20instantiate_20a_20tdl_20to_20hold_20up_20to_20256_20delays_14',['Example : Code snippet to instantiate a TDL to hold up to 256 delays.',['../qtdl_desc.html#qtdl_ex1',1,'']]],
  ['transcendental_20functions_15',['Exponential and transcendental functions',['../qfp16_desc.html#qfp16_exp_functions',1,'']]],
  ['transfer_20function_16',['transfer function',['../qltisys_desc.html#qltisys_ex1',1,'Example: Evaluate the given continuous transfer function'],['../qltisys_desc.html#qltisys_ex2',1,'Example: Evaluate the given discrete transfer function']]],
  ['transfer_20functions_17',['transfer functions',['../qltisys_desc.html#qltisys_cont',1,'Continous-time transfer functions'],['../qltisys_desc.html#qltisys_disc',1,'Discrete-time transfer functions'],['../qltisys_desc.html',1,'Recursive LTI Systems Evaluation by transfer functions.']]],
  ['transport_20delay_18',['Transport-Delay',['../qltisys_desc.html#qltisys_transportdelay',1,'']]],
  ['trigonometric_20functions_19',['Trigonometric functions',['../qffmath_desc.html#qffmath_trig',1,'']]],
  ['trigonometric_20functions_20and_20helpers_20',['Trigonometric functions and helpers',['../qfp16_desc.html#qfp16_trig_functions',1,'']]],
  ['tsukamoto_21',['Tsukamoto',['../qfis_desc.html#qfis_tsukamoto',1,'']]]
];
