name: publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: create dirs
      run: mkdir docout
    - name: set repo url on corner
      run: sed -i 's,https://github.com/jothepro/doxygen-awesome-css,https://github.com/kmilo17pet/qlibs-cpp,g' doc/stylesheet/doxygen-custom/header.html
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@edge
      with:
        doxyfile-path: './doc/Doxyfile'
    - name: rm gitignore
      run: rm .gitignore
    - name: Publish generated content to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
      with:
        dir: ./doxyout/html
        branch: gh-pages
        token: ${{ secrets.ACCESS_TOKEN }}
